### ISSUE TITLE
Big-banged I2C LCD for Raspberry PI doesn't work when run as root

### ISSUE THREAD

**Issue by mrock99** [electronicayciencia/wPi_soft_lcd#1] opened 2021-01-12 00:30 UTC
The soft_lcd works fine for me in my application however if I start my application via rc.local it fails since it is run by root.
To repro you can simply run the example_basic executable as pi and again with sudo. It works fine when run as pi but when run as sudo the following messages appear:
Warning: I2C Bus busy or defective. SDA doesn't go UP after reset.
Warning: I2C Bus busy or defective. SDA doesn't go UP after reset.
Warning: I2C Bus busy or defective. Pin 9 is LOW for 5s.
Warning: I2C Bus busy or defective. Pin 9 is LOW for 5s.
Warning: I2C Bus busy or defective. Pin 9 is LOW for 5s.
Warning: I2C Bus busy or defective. Pin 9 is LOW for 5s.

The program fails to run in this case. 
The i2c_dev and i2c_bcm2708 modules are not loaded.
As a work-around I now run my application as pi in rc.local

OS info:
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Linux 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux

**Comment by electronicayciencia** [comment] 2021-01-12 20:11
Hello mrock99. 

Seems to be the [wPi_soft_i2c backend](https://github.com/electronicayciencia/wPi_soft_i2c) complaining about I2C communication. 

I can't test wPi_soft_lcd right now. But I tested soft_i2c library and it does work as root:

    pi@raspberrypi:~/soft_i2c$ ./scan
    I2C scan for soft_i2c project
     * Device found at 40h
	 
    pi@raspberrypi:~/soft_i2c$ sudo ./scan
    I2C scan for soft_i2c project
     * Device found at 40h

My version of Raspbian is a bit outdated (8.0) and I didn't test the software in 10.

I assume you use pins 9 and 8 for SCL and SDA. Can you, please, reproduce the problem using different pins like 3 and 6 or 23 and 24?

Thank you.

**Comment by mrock99** [comment] 2021-01-14 01:41
Hi electronicayciencia,
Yes, you are right I was using pins 9 (SCL) and 8 (SDA). I tried your suggestion and altered my circuit to use pins 23 and 24. I had the same result. However I noticed that running my program on a Pi 3B+ worked correctly as root as well as pi. I have been doing my development work on a Pi 4B. Once I realized this I found out that there is a newer version (2.52) for the wiringPi s/w to support the Pi 4B. I downloaded it and success! The soft_lcd s/w works on the Pi 4B now regardless of which pins are used and running as root or pi. I apologize for raising this issue. It is not a problem with the soft_lcd s/w. Sorry...

But I would like to say how pleased I am with the soft_lcd s/w. Until recently I was using some other open source lcd driver s/w that turned out to not be reliable. When I integrated your soft_lcd into my application it has been rock solid. Thanks for you work. High quality software.

**Comment by electronicayciencia** [comment] 2021-01-14 20:08
Thank you for your debugging steps and also for your kind words. 

You can actually use this library without the wiringPi backend. You just need to provide your own routines for I2C stuff (i2c_start, i2c_stop, i2c_send_byte and i2c_read_byte) and for delay (usleep). I have been using it inside a PIC16F88 [here](https://github.com/electronicayciencia/termogeiger/blob/master/firmware/counter-lcd/soft_lcd.c) and with an ESP8266 [here](https://github.com/electronicayciencia/esp8266-learning/blob/main/esp_bus/main/soft_lcd.c).

I am closing the issue now. If you have any comment or question, feel free to contact me again.

**Closed as completed by electronicayciencia** 2021-01-14 20:08 UTC
